import type { Metadata } from "next";
import { Inter, Source_Serif_4, Playfair_Display, Open_Sans, Ibarra_Real_Nova } from "next/font/google";
import "./globals.css";
import PageIndicator from "../compenents/page-indicator";
import Footer from "../compenents/footer";import NavigationMobile from "../compenents/navigation-mobile";
import ClientLayout from "../compenents/client-layout";
import localFont from "next/font/local";

const primary = Inter({
  variable: '--font-primary',
  subsets: ["latin"],
    display: 'swap',
});

const secondary = Open_Sans({
  weight: '400',
  variable: '--font-secondary',
  subsets: ["latin"],
    display: 'swap',
});

// const tertiary = Ibarra_Real_Nova({
//   weight: '400',
//   variable: '--font-tertiary',
//   subsets: ["latin"],
//     display: 'swap',
// });

const tertiary = localFont({
  src: [
    { path: '../assets/fonts/Dauphin.ttf', weight: '400', style: 'normal' }, ],
  variable: '--font-tertiary',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`w-screen h-screen p-4 flex flex-col gap-3 pb-2 ${primary.variable} ${secondary.variable} ${tertiary.variable} antialiased`}
      >
        <main className="border-border border w-full h-full flex flex-col">
            <ClientLayout />
            <PageIndicator />
            <section className=" overflow-auto">{children}</section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
