import type { Metadata } from "next";
import { Inter, Space_Grotesk  } from "next/font/google";
import "./globals.css";
import PageIndicator from "../compenents/page-indicator";
import Footer from "../compenents/footer";import NavigationMobile from "../compenents/navigation-mobile";
import ClientLayout from "../compenents/client-layout";

const inter = Inter({
  variable: '--font-primary',
  subsets: ["latin"],
    display: 'swap',
});

const spaceGrotesk = Space_Grotesk({
  variable: '--font-secondary',
  subsets: ["latin"],
    display: 'swap',
});

export const metadata: Metadata = {
  title: "Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`w-screen h-screen p-4 flex flex-col gap-3 pb-2 ${inter.variable} ${spaceGrotesk.variable} antialiased`}
      >
        <main className="border-border border w-full h-full flex flex-col">
            <ClientLayout />
            <PageIndicator />
            <section className=" overflow-auto">{children}</section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
